spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true
    username: root
    password: 121314
  application:
    name: user-center
server:
  port: 8080
  servlet:
#    context-path: /api
    session:
      timeout: 86400
mybatis-plus:
  configuration:
#    驼峰式命名的实体名和字段名，mybatis-plus默认处理是通过下划线分隔；默认是true.
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
